name: ci

on:
  push:
  schedule:
    - cron: "0 9 * * TUE"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    
    -
        name: Checkout
        uses: actions/checkout@v3
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1        
    - 
      name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
      with:
        config-inline: |
          [worker.oci]
              platforms = [ "linux/amd64", "linux/arm64"  ]
    - 
      name: Docker login
      run: echo ${{ secrets.DOCKER_HUB }} | docker login -u pfremm --password-stdin              
    - 
      name: Build
      run: |
        docker buildx build . -t pfremm/auto-southwest-check-in --push --platform=linux/arm64
