name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
      with:
        config-inline: |
          [worker.oci]
              platforms = [ "linux/amd64", "linux/arm64" ]
    - name: Build
      run: |
          docker build . --file ./Dockerfile --tag pfremm:auto-southwest-check-in-docker
